win-dshow: Implement FindPin
obsproject/libdshowcapture pull request #32
Opened 2021-05-20 15:19 UTC by berndfuhrmann

* Implement IBaseFilter::FindPin for output-filter and capture-filter

### Description
For output-filter and capture-filter, this PR implements IBaseFilter:FindPin. Since those filters will only have
one pin, it will compare the pins name with the given id and just return that pin. Handling occurs according to the [Microsoft Docs on FindPin](https://docs.microsoft.com/en-us/windows/win32/api/strmif/nf-strmif-ibasefilter-findpin).

### Motivation and Context

This fixes https://github.com/obsproject/obs-studio/issues/4721.

### How Has This Been Tested?
This should not affect any other areas. In a test program, I called FindPin with different strings for id (some matching, others not) and null and also some IPin* or null. Everything worked according to the FindPin docs. I tested output filter, but capture filter works exactly the same.

### Types of changes
Bug fix

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2021-05-20 16:34 UTC, RytoEX requested changes
This code doesn't know what the OBS Studio win-dshow plugin is.  The commit message doesn't need that prefix.

The commit message body only has one item, so I don't think you need to use a bulleted list.

2021-05-20 19:28 UTC, berndfuhrmann commented
@RytoEX Thanks for your advice. Prefix and bulleted list removed.

2021-05-29 12:09 UTC, WizardCM commented
Would you be able to find or create an example program to test this with?

2021-06-05 10:32 UTC, berndfuhrmann commented
@WizardCM I just wrote one. You can find it here: https://github.com/berndfuhrmann/libdshow-Test-FindPin. Please adjust the GUID in Test-FindPin.cpp to whatever GUID `OBS Virtual Camera` has. I mentioned the different expected HResults in comments in the source code. This only tests `FindPin` of `OutputFilter`. If you think it's necessary, I can also create one for `CaptureFilter`, but the logic is really just the same. Just more complex for me to instantiate the filter 😄. Please let me know what you think.

2021-11-27 23:20 UTC, merged